package eu.telecom_bretagne.cabinet_recrutement.data.model;
// Generated Jan 30, 2023, 1:34:02 PM by Hibernate Tools 5.4.20.Final


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OffreEmploi generated by hbm2java
 */
@Entity
@Table(name="offre_emploi"
    ,schema="public"
)
public class OffreEmploi  implements java.io.Serializable {


     private int idOffre;
     private NiveauQualification niveauQualification;
     private int idEntreprise;
     private String titre;
     private String descriptionMission;
     private String profilRecherche;
     private Date dateDepot;
     private Set<MessageCandidature> messageCandidatures = new HashSet<MessageCandidature>(0);
     private Set<SecteurActivite> secteurActivites = new HashSet<SecteurActivite>(0);
     private Set<MessageOffreEmploi> messageOffreEmplois = new HashSet<MessageOffreEmploi>(0);

    public OffreEmploi() {
    }

	
    public OffreEmploi(int idOffre, NiveauQualification niveauQualification, int idEntreprise, String titre, Date dateDepot) {
        this.idOffre = idOffre;
        this.niveauQualification = niveauQualification;
        this.idEntreprise = idEntreprise;
        this.titre = titre;
        this.dateDepot = dateDepot;
    }
    public OffreEmploi(int idOffre, NiveauQualification niveauQualification, int idEntreprise, String titre, String descriptionMission, String profilRecherche, Date dateDepot, Set<MessageCandidature> messageCandidatures, Set<SecteurActivite> secteurActivites, Set<MessageOffreEmploi> messageOffreEmplois) {
       this.idOffre = idOffre;
       this.niveauQualification = niveauQualification;
       this.idEntreprise = idEntreprise;
       this.titre = titre;
       this.descriptionMission = descriptionMission;
       this.profilRecherche = profilRecherche;
       this.dateDepot = dateDepot;
       this.messageCandidatures = messageCandidatures;
       this.secteurActivites = secteurActivites;
       this.messageOffreEmplois = messageOffreEmplois;
    }
   
     @Id 

    
    @Column(name="id_offre", unique=true, nullable=false)
    public int getIdOffre() {
        return this.idOffre;
    }
    
    public void setIdOffre(int idOffre) {
        this.idOffre = idOffre;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_qualification", nullable=false)
    public NiveauQualification getNiveauQualification() {
        return this.niveauQualification;
    }
    
    public void setNiveauQualification(NiveauQualification niveauQualification) {
        this.niveauQualification = niveauQualification;
    }

    
    @Column(name="id_entreprise", nullable=false)
    public int getIdEntreprise() {
        return this.idEntreprise;
    }
    
    public void setIdEntreprise(int idEntreprise) {
        this.idEntreprise = idEntreprise;
    }

    
    @Column(name="titre", nullable=false, length=50)
    public String getTitre() {
        return this.titre;
    }
    
    public void setTitre(String titre) {
        this.titre = titre;
    }

    
    @Column(name="description_mission")
    public String getDescriptionMission() {
        return this.descriptionMission;
    }
    
    public void setDescriptionMission(String descriptionMission) {
        this.descriptionMission = descriptionMission;
    }

    
    @Column(name="profil_recherche")
    public String getProfilRecherche() {
        return this.profilRecherche;
    }
    
    public void setProfilRecherche(String profilRecherche) {
        this.profilRecherche = profilRecherche;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="date_depot", nullable=false, length=13)
    public Date getDateDepot() {
        return this.dateDepot;
    }
    
    public void setDateDepot(Date dateDepot) {
        this.dateDepot = dateDepot;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="offreEmploi")
    public Set<MessageCandidature> getMessageCandidatures() {
        return this.messageCandidatures;
    }
    
    public void setMessageCandidatures(Set<MessageCandidature> messageCandidatures) {
        this.messageCandidatures = messageCandidatures;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="index_offre_secteur", schema="public", joinColumns = { 
        @JoinColumn(name="id_offre", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="id_secteur", nullable=false, updatable=false) })
    public Set<SecteurActivite> getSecteurActivites() {
        return this.secteurActivites;
    }
    
    public void setSecteurActivites(Set<SecteurActivite> secteurActivites) {
        this.secteurActivites = secteurActivites;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="offreEmploi")
    public Set<MessageOffreEmploi> getMessageOffreEmplois() {
        return this.messageOffreEmplois;
    }
    
    public void setMessageOffreEmplois(Set<MessageOffreEmploi> messageOffreEmplois) {
        this.messageOffreEmplois = messageOffreEmplois;
    }




}


