package eu.telecom_bretagne.cabinet_recrutement.data.model;
// Generated Jan 30, 2023, 1:34:02 PM by Hibernate Tools 5.4.20.Final


import java.util.HashSet;
import java.util.Set;
import jakarta.persistence.*;

/**
 * SecteurActivite generated by hbm2java
 */
@Entity
@NamedQuery(name="SecteurActivite.findAll", query="SELECT sa FROM SecteurActivite sa")
@Table(name="secteur_activite"
    ,schema="public"
)
public class SecteurActivite  implements java.io.Serializable {


     private int idSecteur;
     private String intitule;
     private Set<Candidature> candidatures = new HashSet<Candidature>(0);
     private Set<OffreEmploi> offreEmplois = new HashSet<OffreEmploi>(0);

    public SecteurActivite() {
    }

	
    public SecteurActivite(int idSecteur, String intitule) {
        this.idSecteur = idSecteur;
        this.intitule = intitule;
    }
    public SecteurActivite(int idSecteur, String intitule, Set<Candidature> candidatures, Set<OffreEmploi> offreEmplois) {
       this.idSecteur = idSecteur;
       this.intitule = intitule;
       this.candidatures = candidatures;
       this.offreEmplois = offreEmplois;
    }
   
     @Id
     @SequenceGenerator(name="SECTEUR_ACTIVITE_ID_GENERATOR", sequenceName="SECTEUR_ACTIVITE_ID_SEQ", allocationSize=1)
     @GeneratedValue(strategy=GenerationType.SEQUENCE, generator="SECTEUR_ACTIVITE_ID_GENERATOR") private Integer id;

    
    @Column(name="id_secteur", unique=true, nullable=false)
    public int getIdSecteur() {
        return this.idSecteur;
    }
    
    public void setIdSecteur(int idSecteur) {
        this.idSecteur = idSecteur;
    }

    
    @Column(name="intitule", nullable=false)
    public String getIntitule() {
        return this.intitule;
    }
    
    public void setIntitule(String intitule) {
        this.intitule = intitule;
    }

@ManyToMany(fetch=FetchType.LAZY, mappedBy="secteurActivites")
    public Set<Candidature> getCandidatures() {
        return this.candidatures;
    }
    
    public void setCandidatures(Set<Candidature> candidatures) {
        this.candidatures = candidatures;
    }

@ManyToMany(fetch=FetchType.LAZY, mappedBy="secteurActivites")
    public Set<OffreEmploi> getOffreEmplois() {
        return this.offreEmplois;
    }
    
    public void setOffreEmplois(Set<OffreEmploi> offreEmplois) {
        this.offreEmplois = offreEmplois;
    }




}


